import streamlit as st
import pandas as pd
import openpyxl

st.set_page_config(page_title="APP MANU", page_icon="📄", layout="wide")

# Chemin vers le fichier Excel
fichier_path = 'fichier.xlsx'

def load_data():
    return pd.read_excel(fichier_path)

def update_excel(chapitre, termine):
    book = openpyxl.load_workbook(fichier_path)
    sheet = book.active
    
    # Trouver la ligne correspondante au chapitre
    for row in range(2, sheet.max_row + 1):
        if sheet[f'A{row}'].value == chapitre:
            sheet[f'B{row}'] = termine
            break
    
    book.save(fichier_path)
    book.close()
    return load_data()  # Retourne les données mises à jour

def update_progression(data):
    # Mise à jour de la progression dans st.session_state
    st.session_state.progression = sum(data["Terminé"] * data["Pourcentage évolution"])

# Initialisation de la progression avec les données actuelles du fichier Excel
if 'progression' not in st.session_state:
    data_initiale = load_data()
    update_progression(data_initiale)

def main():
    st.title(":blue[Hello Emma] 👋,Explore les Chapitres du livre de Daniel 😎")
    data = load_data()

    col1, col2 = st.columns([3, 1])

    with col1:
        chapitre_choice = st.selectbox("Choisi un chapitre 😊", data["CHAPITRES"])
        chapitre_info = data[data["CHAPITRES"] == chapitre_choice].iloc[0]
        
        # Affichage simulé du contenu du chapitre
        st.write(f"Contenu du Chapitre {chapitre_choice}")
        if chapitre_choice == 1:
            st.write(":red[01] LA TROISIEME ANNEE du règne de Joakim, roi de Juda, Nabucodonosor, roi de Babylone, arriva devant Jérusalem et l’assiégea.")
            st.write(":red[02] Le Seigneur livra entre ses mains Joakim, roi de Juda, ainsi qu’une partie des objets de la Maison de Dieu. Il les emporta au pays de Babylone, et les déposa dans le trésor de ses dieux.")
            st.write(":red[03] Le roi ordonna à Ashpénaz, chef de ses eunuques, de faire venir quelques jeunes Israélites de race royale ou de famille noble.")
            st.write(":red[04] Ils devaient être sans défaut corporel, de belle figure, exercés à la sagesse, instruits et intelligents, pleins de vigueur, pour se tenir à la cour du roi et apprendre l’écriture et la langue des Chaldéens.")
            st.write(":red[05] Le roi leur assignait pour chaque jour une portion des mets royaux et du vin de sa table. Ils devaient être formés pendant trois ans, et ensuite ils entreraient au service du roi.")
            st.write(":red[06] Parmi eux se trouvaient Daniel, Ananias, Misaël et Azarias, qui étaient de la tribu de Juda.")
            st.write(":red[07] Le chef des eunuques leur imposa des noms : à Daniel celui de Beltassar, à Ananias celui de Sidrac, à Misaël celui de Misac, et à Azarias celui d’Abdénago.")
            st.write(":red[08] Daniel eut à cœur de ne pas se souiller avec les mets du roi et le vin de sa table, il supplia le chef des eunuques de lui épargner cette souillure.")
            st.write(":red[09] Dieu permit à Daniel de trouver auprès de celui-ci faveur et bienveillance.")
            st.write(":red[10] Mais il répondit à Daniel : « J’ai peur de mon Seigneur le roi, qui a fixé votre nourriture et votre boisson ; s’il vous voit le visage plus défait qu’aux jeunes gens de votre âge, c’est moi qui, à cause de vous, risquerai ma tête devant le roi. »")
            st.write(":red[11] Or, le chef des eunuques avait confié Daniel, Ananias, Azarias et Misaël à un intendant. Daniel lui dit :")
            st.write(":red[12] « Fais donc pendant dix jours un essai avec tes serviteurs : qu’on nous donne des légumes à manger et de l’eau à boire.")
            st.write(":red[13] Tu pourras comparer notre mine avec celle des jeunes gens qui mangent les mets du roi, et tu agiras avec tes serviteurs suivant ce que tu auras constaté. »")
            st.write(":red[14] L’intendant consentit à leur demande, et les mit à l’essai pendant dix jours.")
            st.write(":red[15] Au bout de dix jours, ils avaient plus belle mine et meilleure santé que tous les jeunes gens qui mangeaient des mets du roi.")
            st.write(":red[16] L’intendant supprima définitivement leurs mets et leur ration de vin, et leur fit donner des légumes.")
            st.write(":red[17] À ces quatre jeunes gens, Dieu accorda science et habileté en matière d’écriture et de sagesse. Daniel, en outre, savait interpréter les visions et les songes.")
            st.write(":red[18] Au terme fixé par le roi Nabucodonosor pour qu’on lui amenât tous les jeunes gens, le chef des eunuques les conduisit devant lui.")
            st.write(":red[19] Le roi s’entretint avec eux, et pas un seul n’était comparable à Daniel, Ananias, Misaël et Azarias. Ils entrèrent donc au service du roi.")
            st.write(":red[20] Sur toutes les questions demandant sagesse et intelligence que le roi leur posait, il les trouvait dix fois supérieurs à tous les magiciens et mages de tout son royaume.")
            st.write(":red[21] Et Daniel vécut jusqu’à la première année du roi Cyrus.")

        elif chapitre_choice == 2:
            st.write(":red[01] La deuxième année de son règne, Nabucodonosor eut des songes, et le sommeil quitta son esprit troublé.")
            st.write(":red[02] Le roi fit appeler les magiciens, les mages, les enchanteurs et les devins, pour qu’ils interprètent les songes du roi. Ils arrivèrent et se tinrent en présence du roi.")
            st.write(":red[03] Le roi leur dit : « J’ai eu un songe, et mon esprit est troublé par le désir de le comprendre. »")
            st.write(":red[04] Les devins dirent au roi en araméen : « Ô roi, puisses-tu vivre à jamais ! Raconte le songe à tes serviteurs, et nous en donnerons l’interprétation. »")
            st.write(":red[05] Le roi répondit aux devins : « Je n’ai qu’une parole ! Faites-moi connaître le songe et son interprétation, sinon vous serez mis en pièces et vos maisons ne seront plus que décombres.")
            st.write(":red[06] Par contre, si vous me faites connaître le songe et son interprétation, vous recevrez de moi des cadeaux, des récompenses et de grands honneurs. Faites-moi donc connaître le songe et son interprétation. »")
            st.write(":red[07] Pour la deuxième fois, ils répondirent : « Que le roi dise le songe à ses serviteurs, et nous en ferons connaître l’interprétation. »")
            st.write(":red[08] Mais le roi répondit : « Bien entendu, vous cherchez à gagner du temps, maintenant que j’ai donné ma parole !")
            st.write(":red[09] Si vous ne me faites pas connaître le songe, il n’y aura pour vous qu’une seule sentence. Vous êtes complices et vous me tenez des discours mensongers et retors pour tromper le temps. Racontez-moi le songe, et je saurai que vous m’en ferez connaître l’interprétation. »")
            st.write(":red[10] Les devins répondirent au roi : « Personne au monde ne peut faire connaître ce que demande le roi. D’ailleurs, aucun roi, si grand et si puissant soit-il, n’a encore demandé une chose pareille à un magicien, un mage ou un devin.")
            st.write(":red[11] Ce que le roi demande est si difficile que seuls les dieux, dont la demeure n’est pas parmi les hommes, pourraient le faire connaître au roi. »")
            st.write(":red[12] Alors, le roi laissa exploser une terrible colère, et il ordonna de faire exécuter tous les sages de Babylone.")
            st.write(":red[13] La condamnation à mort des sages fut promulguée, et l’on fit chercher Daniel et ses compagnons pour les faire mourir.")
            st.write(":red[14] Mais Daniel, en des paroles sages et prudentes, s’adressa à Aryok, chef des gardes du roi, qui s’apprêtait à faire mourir les sages de Babylone.")
            st.write(":red[15] Il parla ainsi à Aryok, l’officier du roi : « Pourquoi la sentence du roi est-elle si dure ? » Et Aryok l’expliqua à Daniel.")
            st.write(":red[16] Daniel alla demander au roi de lui accorder un délai pour faire connaître au roi l’interprétation du songe.")
            st.write(":red[17] Puis, Daniel retourna chez lui et mit au courant de l’affaire Ananias, Misaël et Azarias, ses compagnons.")
            st.write(":red[18] Il leur demanda d’implorer la miséricorde du Dieu du ciel à propos de ce mystère, pour qu’on n’exécute pas Daniel et ses compagnons avec les autres sages de Babylone.")
            st.write(":red[19] Alors, dans une vision nocturne, le mystère fut révélé à Daniel. Et Daniel bénit le Dieu du ciel.")
            st.write(":red[20] Daniel prit la parole et dit : « Béni soit le nom de Dieu depuis toujours et à jamais. À lui la sagesse et la force !")
            st.write(":red[21] Lui qui fait changer les âges et les temps, il renverse des rois, il en établit d’autres ; aux sages il donne la sagesse, et l’intelligence à ceux qui savent discerner.")
            st.write(":red[22] Lui qui révèle profondeurs et secrets, il connaît ce qui est dans les ténèbres, et la lumière demeure auprès de lui.")
            st.write(":red[23] À toi, Dieu de mes pères, mon action de grâce et ma louange, car tu m’as donné la sagesse et la force, et maintenant tu m’as fait connaître ce que nous t’avons demandé, puisque tu nous as fait connaître ce qui concerne le roi. »")
            st.write(":red[24] Après quoi, Daniel alla chez Aryok, que le roi avait chargé d’exécuter les sages de Babylone. Il entra et lui parla ainsi : « N’exécute pas les sages de Babylone ! Conduis-moi devant le roi. Je ferai connaître au roi l’interprétation du songe. »")
            st.write(":red[25] En toute hâte, Aryok conduisit Daniel devant le roi et lui parla ainsi : « Parmi les déportés de Juda, j’ai trouvé un homme qui donnera l’interprétation au roi. »")
            st.write(":red[26] Prenant la parole, le roi dit à Daniel, surnommé Beltassar : « Peux-tu me faire connaître ce que j’ai vu en songe et son interprétation ? »")
            st.write(":red[27] En présence du roi, Daniel répondit : « Le mystère sur lequel le roi s’interroge, des sages, des mages, des magiciens ou des astrologues ne peuvent le faire connaître au roi.")
            st.write(":red[28] Mais, dans les cieux, il y a un Dieu qui révèle les mystères et fait connaître au roi Nabucodonosor ce qui arrivera à la fin des jours. Ton songe et les visions de ton esprit sur ton lit, les voici.")
            st.write(":red[29] Ô roi, sur ton lit, des pensées ont surgi à ton esprit au sujet de ce qui arrivera par la suite. Celui qui révèle les mystères t’a fait connaître ce qui arrivera.")
            st.write(":red[30] Quant à moi, ce n’est pas à cause d’une sagesse qui, en moi, serait supérieure à celle de tout être vivant, que le mystère m’a été révélé ; mais c’est afin que l’on fasse connaître au roi l’interprétation, et que tu connaisses les pensées de ton cœur.")
            st.write(":red[31] Ô roi, voici ta vision : une énorme statue se dressait devant toi, une grande statue, extrêmement brillante et d’un aspect terrifiant.")
            st.write(":red[32] Elle avait la tête en or fin ; la poitrine et les bras, en argent ; le ventre et les cuisses, en bronze ;")
            st.write(":red[33] ses jambes étaient en fer, et ses pieds, en partie de fer, en partie d’argile.")
            st.write(":red[34] Tu étais en train de regarder : soudain une pierre se détacha d’une montagne, sans qu’on y ait touché ; elle vint frapper les pieds de fer et d’argile de la statue et les pulvérisa.")
            st.write(":red[35] Alors furent pulvérisés tout ensemble le fer et l’argile, le bronze, l’argent et l’or ; ils devinrent comme la paille qui s’envole en été, au moment du battage : ils furent emportés par le vent sans laisser de traces. Quant à la pierre qui avait frappé la statue, elle devint un énorme rocher qui remplit toute la terre.")
            st.write(":red[36] Voici le songe ; et maintenant, en présence du roi, nous allons en donner l’interprétation.")
            st.write(":red[37] C’est à toi, le roi des rois, que le Dieu du ciel a donné royauté, puissance, force et gloire.")
            st.write(":red[38] C’est à toi qu’il a remis les enfants des hommes, les bêtes des champs et les oiseaux du ciel, quelle que soit leur demeure ; c’est toi qu’il a rendu maître de toute chose : la tête d’or, c’est toi.")
            st.write(":red[39] Après toi s’élèvera un autre royaume inférieur au tien, ensuite un troisième royaume, un royaume de bronze qui dominera la terre entière.")
            st.write(":red[40] Il y aura encore un quatrième royaume, dur comme le fer. De même que le fer brise et écrase tout, de même, il pulvérisera et brisera tous les royaumes.")
            st.write(":red[41] Tu as vu les pieds qui étaient en partie d’argile et en partie de fer : en effet, ce royaume sera divisé ; il aura en lui la force du fer, comme tu as vu du fer mêlé à l’argile.")
            st.write(":red[42] Ces pieds en partie de fer et en partie d’argile signifient que le royaume sera en partie fort et en partie faible.")
            st.write(":red[43] Tu as vu le fer associé à l’argile parce que les royaumes s’uniront par des mariages ; mais ils ne tiendront pas ensemble, de même que le fer n’adhère pas à l’argile.")
            st.write(":red[44] Or, au temps de ces rois, le Dieu du ciel suscitera un royaume qui ne sera jamais détruit, et dont la royauté ne passera pas à un autre peuple. Ce dernier royaume pulvérisera et anéantira tous les autres, mais lui-même subsistera à jamais.")
            st.write(":red[45] C’est ainsi que tu as vu une pierre se détacher de la montagne sans qu’on y ait touché, et pulvériser le fer, le bronze, l’argile, l’argent et l’or. Le grand Dieu a fait connaître au roi ce qui doit ensuite advenir. Le songe disait vrai, l’interprétation est digne de foi. »")
            st.write(":red[46] Alors, le roi Nabucodonosor tomba face contre terre. Se prosternant devant Daniel, il ordonna qu’on lui présente une offrande de céréales et un sacrifice d’agréable odeur.")
            st.write(":red[47] Le roi prit la parole et dit à Daniel : « En vérité, votre Dieu est le Dieu des dieux, le Seigneur des rois, celui qui révèle les mystères, puisque tu as su nous révéler ce mystère. »")
            st.write(":red[48] Puis le roi conféra un rang élevé à Daniel et lui offrit de riches et nombreux cadeaux. Il lui donna autorité sur toute la province de Babylone et en fit le préfet suprême de tous les sages de Babylone.")
            st.write(":red[49] Daniel demanda au roi de confier l’administration de la province de Babylone à Sidrac, Misac et Abdénago. Quant à Daniel, il était à la cour du roi.")

        elif chapitre_choice == 3:
            st.write(":red[01] Le roi Nabucodonosor fit une statue d’or : elle était haute de soixante coudées, large de six coudées. Il l’érigea dans la plaine de Doura, dans la province de Babylone.")
            st.write(":red[02] Le roi Nabucodonosor fit rassembler les satrapes, les préfets, les gouverneurs, les conseillers, les trésoriers, les juges, les magistrats et tous les fonctionnaires des provinces, pour qu’ils viennent à l’inauguration de la statue érigée par le roi Nabucodonosor.")
            st.write(":red[03] Alors, les satrapes, les préfets, les gouverneurs, les conseillers, les trésoriers, les juges, les magistrats et tous les fonctionnaires des provinces se rassemblèrent pour l’inauguration de la statue qu’avait érigée le roi Nabucodonosor. Ils se tenaient là, debout, devant la statue que le roi Nabucodonosor avait érigée.")
            st.write(":red[04] Le crieur public proclama avec force : « Vous, peuples, nations et gens de toutes langues, on vous l’ordonne :")
            st.write(":red[05] Quand vous entendrez le son du cor, de la flûte, de la cithare, de la harpe, de la lyre, de la cornemuse et de toutes les sortes d’instruments, vous vous prosternerez et vous adorerez la statue d’or que le roi Nabucodonosor a érigée.")
            st.write(":red[06] Celui qui ne se prosternera pas et n’adorera pas sera jeté immédiatement au milieu d’une fournaise de feu ardent. »")
            st.write(":red[07] Alors, à l’instant même où tous entendirent le son du cor, de la flûte, de la cithare, de la harpe, de la lyre, de la cornemuse et de toutes les sortes d’instruments, tous les peuples, nations et gens de toutes langues se prosternèrent et adorèrent la statue d’or que le roi Nabucodonosor avait érigée.")
            st.write(":red[08] Là-dessus, à ce moment, des devins s’approchèrent pour dénoncer les Juifs.")
            st.write(":red[09] Prenant la parole, ils dirent à Nabucodonosor : « Ô roi, puisses-tu vivre à jamais !")
            st.write(":red[10] Toi, ô roi, tu as ordonné que tout homme qui entendrait le son du cor, de la flûte, de la cithare, de la harpe, de la lyre, de la cornemuse et de toutes les sortes d’instruments se prosternerait pour adorer la statue d’or.")
            st.write(":red[11] Celui qui ne se prosternerait pas et n’adorerait pas serait jeté au milieu d’une fournaise de feu ardent.")
            st.write(":red[12] Tu as confié l’administration de la province de Babylone à des Juifs : Sidrac, Misac et Abdénago. Eh bien, ô roi, ces hommes n’ont pas tenu compte de toi ! Ils ne servent pas tes dieux, ils n’adorent pas la statue d’or que tu as érigée. »")
            st.write(":red[13] Alors Nabucodonosor, pris d’une violente colère, ordonna qu’on lui amène Sidrac, Misac et Abdénago. Et ces hommes furent amenés devant le roi.")
            st.write(":red[14] Le roi Nabucodonosor leur parla ainsi : « Est-il vrai, Sidrac, Misac et Abdénago, que vous refusez de servir mes dieux et d’adorer la statue d’or que j’ai fait ériger ?")
            st.write(":red[15] Êtes-vous prêts, maintenant, à vous prosterner pour adorer la statue que j’ai faite, quand vous entendrez le son du cor, de la flûte, de la cithare, de la harpe, de la lyre, de la cornemuse et de toutes les sortes d’instruments ? Si vous n’adorez pas cette statue, vous serez immédiatement jetés dans la fournaise de feu ardent ; et quel est le dieu qui vous délivrera de ma main ? »")
            st.write(":red[16] Sidrac, Misac et Abdénago dirent au roi Nabucodonosor : « Ce n’est pas à nous de te répondre.")
            st.write(":red[17] Si notre Dieu, que nous servons, peut nous délivrer, il nous délivrera de la fournaise de feu ardent et de ta main, , ô roi.")
            st.write(":red[18] Et même s’il ne le fait pas, sois-en bien sûr, ô roi : nous ne servirons pas tes dieux, nous n’adorerons pas la statue d’or que tu as érigée. »")
            st.write(":red[19] Alors Nabucodonosor fut rempli de fureur contre Sidrac, Misac et Abdénago, et son visage s’altéra. Il ordonna de chauffer la fournaise sept fois plus qu’à l’ordinaire.")
            st.write(":red[20] Puis il ordonna aux plus vigoureux de ses soldats de ligoter Sidrac, Misac et Abdénago et de les jeter dans la fournaise de feu ardent.")
            st.write(":red[21] Alors, on ligota ces hommes, vêtus de leurs manteaux, de leurs tuniques, de leurs bonnets et de leurs autres vêtements, et on les jeta dans la fournaise de feu ardent.")
            st.write(":red[22] Là-dessus, comme l’ordre du roi était strict et la fournaise extrêmement chauffée, la flamme brûla à mort les hommes qui y portaient Sidrac, Misac et Abdénago.")
            st.write(":red[23] Et ces trois hommes, Sidrac, Misac et Abdénago, tombèrent, ligotés, au milieu de la fournaise de feu ardent.")
            st.write(":red[24] Or ils marchaient au milieu des flammes, ils louaient Dieu et bénissaient le Seigneur.")
            st.write(":red[25] Azarias, debout, priait ainsi ; au milieu du feu, ouvrant la bouche, il dit :")
            st.write(":red[26] « Béni sois-tu, Seigneur, Dieu de nos pères, loué sois-tu, glorifié soit ton nom pour les siècles !")
            st.write(":red[27] Oui, tu es juste en tout ce que tu as fait ! [Toutes tes œuvres sont vraies ; ils sont droits, tes chemins, et tous tes jugements sont vérité.")
            st.write(":red[28] Tes sentences de vérité, tu les as exécutées par tout ce que tu nous as infligé, à nous et à Jérusalem, la ville sainte de nos pères. Avec vérité et justice, tu as infligé tout cela à cause de nos péchés.]")
            st.write(":red[29] Car nous avons péché ; quand nous t’avons quitté, nous avons fait le mal : en tout, nous avons failli. [")
            st.write(":red[30] Nous n’avons pas écouté tes commandements, nous n’avons pas observé ni accompli ce qui nous était commandé pour notre bien.")
            st.write(":red[31] Oui, tout ce que tu nous as infligé, tout ce que tu nous as fait, tu l’as fait par un jugement de vérité.")
            st.write(":red[32] Tu nous as livrés aux mains de nos ennemis, gens sans loi, les plus odieux des renégats, à un roi injuste, le pire de toute la terre.")
            st.write(":red[33] Maintenant, nous ne pouvons plus ouvrir la bouche : ceux qui te servent et qui t’adorent n’ont plus en partage que la honte et l’injure.]")
            st.write(":red[34] À cause de ton nom, ne nous livre pas pour toujours et ne romps pas ton alliance.")
            st.write(":red[35] Ne nous retire pas ta miséricorde, à cause d’Abraham, ton ami, d’Isaac, ton serviteur, et d’Israël que tu as consacré.")
            st.write(":red[36] Tu as dit que tu rendrais leur descendance aussi nombreuse que les astres du ciel, que le sable au rivage des mers.")
            st.write(":red[37] Or nous voici, ô Maître, le moins nombreux de tous les peuples, humiliés aujourd’hui sur toute la terre, à cause de nos péchés.")
            st.write(":red[38] Il n’est plus, en ce temps, ni prince ni chef ni prophète, plus d’holocauste ni de sacrifice, plus d’oblation ni d’offrande d’encens, plus de lieu où t’offrir nos prémices pour obtenir ta miséricorde.")
            st.write(":red[39] Mais, avec nos cœurs brisés, nos esprits humiliés, reçois-nous,")
            st.write(":red[40] comme un holocauste de béliers, de taureaux, d’agneaux gras par milliers. Que notre sacrifice, en ce jour, trouve grâce devant toi, car il n’est pas de honte pour qui espère en toi.")
            st.write(":red[41] Et maintenant, de tout cœur, nous te suivons, nous te craignons et nous cherchons ta face.")
            st.write(":red[42] Ne nous laisse pas dans la honte, agis envers nous selon ton indulgence et l’abondance de ta miséricorde.")
            st.write(":red[43] Délivre-nous en renouvelant tes merveilles, glorifie ton nom, Seigneur.")
            st.write(":red[44] Qu’ils soient tous confondus, ceux qui causent du tort à tes serviteurs ! Qu’ils soient couverts de honte, privés de tout pouvoir, et que leur force soit brisée !")
            st.write(":red[45] Qu’ils sachent que toi, tu es le Seigneur, le seul Dieu, glorieux sur toute la terre ! »")
            st.write(":red[46] Les serviteurs du roi qui les avaient jetés dans la fournaise ne cessaient d’alimenter le feu avec du bitume, de la poix, de l’étoupe et des sarments,")
            st.write(":red[47] et la flamme s’élevait de quarante-neuf coudées au-dessus de la fournaise.")
            st.write(":red[48] En se propageant, elle brûla ceux des Chaldéens qu’elle trouva autour de la fournaise.")
            st.write(":red[49] Mais l’ange du Seigneur était descendu dans la fournaise en même temps qu’Azarias et ses compagnons ; la flamme du feu, il l’écarta de la fournaise")
            st.write(":red[50] et fit souffler comme un vent de rosée au milieu de la fournaise. Le feu ne les toucha pas du tout, et ne leur causa ni douleur ni dommage.")
            st.write(":red[51] Puis, d’une seule voix, les trois jeunes gens se mirent à louer, à glorifier et à bénir Dieu en disant :")
            st.write(":red[52] « Béni sois-tu, Seigneur, Dieu de nos pères : à toi, louange et gloire éternellement ! Béni soit le nom très saint de ta gloire : à toi, louange et gloire éternellement !")
            st.write(":red[53] Béni sois-tu dans ton saint temple de gloire : à toi, louange et gloire éternellement !")
            st.write(":red[54] Béni sois-tu sur le trône de ton règne : à toi, louange et gloire éternellement !")
            st.write(":red[55] Béni sois-tu, toi qui sondes les abîmes : à toi, louange et gloire éternellement ! Toi qui sièges au-dessus des Kéroubim : à toi, louange et gloire éternellement !")
            st.write(":red[56] Béni sois-tu au firmament, dans le ciel, à toi, louange et gloire éternellement ! ( 57) Toutes les œuvres du Seigneur, bénissez-le : à toi, louange et gloire éternellement ! »")
            st.write(":red[57] « Toutes les œuvres du Seigneur, bénissez le Seigneur : À lui, haute gloire, louange éternelle !")
            st.write(":red[58] Vous, les anges du Seigneur, bénissez le Seigneur : À lui, haute gloire, louange éternelle !")
            st.write(":red[59] Vous, les cieux, bénissez le Seigneur,")
            st.write(":red[60] et vous, les eaux par-dessus le ciel, bénissez le Seigneur,")
            st.write(":red[61] et toutes les puissances du Seigneur, bénissez le Seigneur !")
            st.write(":red[62] Et vous, le soleil et la lune, bénissez le Seigneur,")
            st.write(":red[63] et vous, les astres du ciel, bénissez le Seigneur,")
            st.write(":red[64] vous toutes, pluies et rosées, bénissez le Seigneur !")
            st.write(":red[65] Vous tous, souffles et vents, bénissez le Seigneur,")
            st.write(":red[66] et vous, le feu et la chaleur, bénissez le Seigneur,")
            st.write(":red[67] et vous, la fraîcheur et le froid, bénissez le Seigneur !")
            st.write(":red[68] Et vous, le givre et la rosée, bénissez le Seigneur,")
            st.write(":red[69] et vous, le gel et le froid, bénissez le Seigneur,")
            st.write(":red[70] et vous, la glace et la neige, bénissez le Seigneur !")
            st.write(":red[71] Et vous, les nuits et les jours, bénissez le Seigneur,")
            st.write(":red[72] et vous, la lumière et les ténèbres, bénissez le Seigneur,")
            st.write(":red[73] et vous, les éclairs, les nuées, bénissez le Seigneur ! À lui, haute gloire, louange éternelle !")
            st.write(":red[74] Que la terre bénisse le Seigneur : À lui, haute gloire, louange éternelle !")
            st.write(":red[75] Et vous, montagnes et collines, bénissez le Seigneur,")
            st.write(":red[76] et vous, les plantes de la terre, bénissez le Seigneur,")
            st.write(":red[77] et vous, sources et fontaines, bénissez le Seigneur !")
            st.write(":red[78] Et vous, océans et rivières, bénissez le Seigneur,")
            st.write(":red[79] baleines et bêtes de la mer, bénissez le Seigneur,")
            st.write(":red[80] vous tous, les oiseaux dans le ciel, bénissez le Seigneur,")
            st.write(":red[81] vous tous, fauves et troupeaux, bénissez le Seigneur : À lui, haute gloire, louange éternelle !")
            st.write(":red[82] Et vous, les enfants des hommes, bénissez le Seigneur : À lui, haute gloire, louange éternelle !")
            st.write(":red[83] Toi, Israël, bénis le Seigneur,")
            st.write(":red[84] Et vous, les prêtres, bénissez le Seigneur,")
            st.write(":red[85] vous, ses serviteurs, bénissez le Seigneur !")
            st.write(":red[86] Les esprits et les âmes des justes, bénissez le Seigneur,")
            st.write(":red[87] les saints et les humbles de cœur, bénissez le Seigneur,")
            st.write(":red[88] Ananias, Azarias et Misaël, bénissez le Seigneur : À lui, haute gloire, louange éternelle ! Il nous a délivrés des enfers, sauvés du pouvoir de la mort, il nous a tirés de la fournaise ardente, retirés du milieu du feu.")
            st.write(":red[89] Rendez grâce au Seigneur : il est bon, éternel est son amour !")
            st.write(":red[90] Vous tous qui adorez le Seigneur, bénissez le Dieu des dieux ; chantez et rendez grâce : éternel est son amour ! »")
            st.write(":red[91] (24) Alors, le roi Nabucodonosor fut stupéfait. Il se leva précipitamment et dit à ses conseillers : « Nous avons bien jeté trois hommes, ligotés, au milieu du feu ? » Ils répondirent : « Assurément, ô roi. »")
            st.write(":red[92] (25) Il reprit : « Eh bien moi, je vois quatre hommes qui se promènent librement au milieu du feu, ils sont parfaitement indemnes, et le quatrième ressemble à un être divin. »")
            st.write(":red[93] (26) Alors Nabucodonosor s’approcha de l’ouverture de la fournaise de feu ardent. Il appela : « Sidrac, Misac et Abdénago, serviteurs du Dieu Très-Haut, sortez et venez ici ! » Alors Sidrac, Misac et Abdénago sortirent du milieu du feu.")
            st.write(":red[94] (27) Les satrapes, les préfets, les gouverneurs et les conseillers du roi, s’étant rassemblés, regardèrent ces hommes : le feu n’avait pas eu de pouvoir sur leurs corps, leurs cheveux n’avaient pas été brûlés, leurs manteaux n’avaient pas été abîmés et l’odeur de feu ne les avait pas imprégnés.")
            st.write(":red[95] (28) Et Nabucodonosor s’écria : « Béni soit le Dieu de Sidrac, Misac et Abdénago, qui a envoyé son ange et délivré ses serviteurs ! Ils ont mis leur confiance en lui, et ils ont désobéi à l’ordre du roi ; ils ont livré leur corps plutôt que de servir et d’adorer un autre dieu que leur Dieu.")
            st.write(":red[96] (29) Voici ce que j’ordonne à tous les peuples, nations et gens de toutes langues : Si quelqu’un parle avec insolence du Dieu de Sidrac, Misac et Abdénago, qu’il soit mis en pièces et sa maison transformée en décombres. Car aucun autre dieu ne peut délivrer de cette manière. »")
            st.write(":red[97] (30) Et le roi assura la prospérité de Sidrac, Misac et Abdénago, dans la province de Babylone.")
            st.write(":red[98] (31) De Nabucodonosor, le roi, à tous les peuples, nations et gens de toutes langues qui habitent sur toute la terre : Paix en abondance !")
            st.write(":red[99] (32) Je veux faire connaître les signes et les merveilles que le Dieu Très-Haut a faits pour moi.")
            st.write(":red[100] (33) Ses signes, comme ils sont grands ! Ses merveilles, comme elles sont puissantes ! Son royaume est un royaume éternel, son pouvoir s’étend d’âge en âge.")

        elif chapitre_choice == 4:
            st.write(":red[01] Moi, Nabucodonosor, j’étais tranquille dans ma maison et satisfait dans mon palais.")
            st.write(":red[02] J’ai eu un songe : il m’a effrayé. Sur mon lit, je fus troublé par des pensées obsédantes et, dans mon esprit, par des visions.")
            st.write(":red[03] J’ai donné l’ordre d’introduire en ma présence tous les sages de Babylone, pour qu’ils me fassent connaître l’interprétation du songe.")
            st.write(":red[04] Alors, les magiciens, les mages, les devins et les astrologues entrèrent, et je leur racontai le songe, mais ils ne m’ont pas fait connaître son interprétation.")
            st.write(":red[05] En dernier lieu, Daniel se présenta devant moi – son nom est Beltassar, selon le nom de mon dieu, et il a en lui l’esprit des dieux saints. Je lui racontai le songe :")
            st.write(":red[06] « Beltassar, chef des magiciens, tu as en toi l’esprit des dieux saints, je le sais, et aucun mystère ne t’embarrasse. Voici le songe que j’ai fait ; dis-moi son interprétation.")
            st.write(":red[07] Sur mon lit, je regardais les visions de mon esprit : Voici un arbre, au milieu de la terre, d’une gigantesque hauteur.")
            st.write(":red[08] L’arbre grandit, et il devint puissant, sa hauteur atteignait le ciel, et on le voyait de toute la terre.")
            st.write(":red[09] Son feuillage était beau et son fruit abondant ; il y avait en lui de la nourriture pour tous. Les animaux sauvages s’abritaient sous lui ; les oiseaux du ciel demeuraient dans ses branches ; toute créature se nourrissait de lui.")
            st.write(":red[10] Sur mon lit, je regardais les visions de mon esprit, lorsqu’un Vigilant, un être saint, descendit du ciel.")
            st.write(":red[11] Il criait à pleine voix : Abattez l’arbre et coupez ses branches ! Arrachez son feuillage et jetez son fruit ! Que les bêtes quittent son abri, et les oiseaux, ses branches !")
            st.write(":red[12] Mais la souche avec les racines, laissez-les dans la terre, dans des chaînes de fer et de bronze, dans l’herbe des champs. L’arbre sera trempé de la rosée du ciel, il partagera avec les bêtes l’herbe de la terre.")
            st.write(":red[13] Son cœur d’homme sera changé, un cœur de bête lui sera donné. Alors, des temps, au nombre de sept, passeront sur lui.")
            st.write(":red[14] Voici la décision arrêtée par les Vigilants, la résolution prise par les êtres saints, pour que les vivants le reconnaissent : le Très-Haut est maître du royaume des hommes ; il le donne à qui il veut, il élève le plus humble des hommes.")
            st.write(":red[15] Tel est le songe que j’ai eu, moi, le roi Nabucodonosor. Toi, Beltassar, donne-moi son interprétation, car aucun des sages de mon royaume n’a pu m’en faire connaître l’interprétation. Mais toi, tu le peux, puisque l’esprit des dieux saints est en toi.")
            st.write(":red[16] Alors Daniel, surnommé Beltassar, resta un instant terrifié, et ses pensées l’épouvantaient. Le roi prit la parole et dit : « Beltassar, que le songe et son interprétation ne t’épouvantent pas ! » Beltassar répondit : « Mon seigneur, que le songe soit pour tes ennemis, et son interprétation pour tes adversaires !")
            st.write(":red[17] L’arbre que tu as vu, grand, puissant, élevé, atteignant le ciel et visible de toute la terre,")
            st.write(":red[18] dont le feuillage était beau et le fruit abondant, en qui il y avait de la nourriture pour tous, sous lequel s’abritaient les animaux sauvages, et dans les branches duquel demeuraient les oiseaux,")
            st.write(":red[19] c’est toi, ô roi ! Tu es devenu grand et puissant, tu as grandi au point d’atteindre le ciel, et ta domination s’étend jusqu’aux extrémités de la terre.")
            st.write(":red[20] Puis, ô roi, tu as vu un Vigilant, un être saint descendu du ciel et qui disait : “Abattez l’arbre et détruisez-le, mais laissez dans la terre la souche avec les racines, dans des chaînes de fer et de bronze, dans l’herbe des champs, et qu’il soit trempé de la rosée du ciel, et partage le sort des animaux sauvages, jusqu’à ce que sept temps passent sur lui.”")
            st.write(":red[21] Cette vision, ô roi, en voici l’interprétation, la décision du Très-Haut qui atteint mon seigneur le roi :")
            st.write(":red[22] Tu seras chassé d’entre les hommes, tu auras ta demeure avec les animaux sauvages, on te nourrira d’herbe, comme les bœufs, tu seras trempé de la rosée du ciel, et sept temps passeront sur toi, jusqu’au moment où tu reconnaîtras que le Très-Haut est maître du royaume des hommes et le donne à qui il veut.")
            st.write(":red[23] Et si l’on a dit de laisser en terre la souche avec les racines de l’arbre, c’est que ta royauté se maintiendra quand tu auras reconnu que le Ciel est le maître.")
            st.write(":red[24] Aussi, que mon conseil te paraisse bon, ô roi : rachète tes péchés par la justice, et tes fautes par la pitié envers les malheureux. S’il en est ainsi, ta tranquillité se prolongera.")
            st.write(":red[25] Tout cela arriva au roi Nabucodonosor.")
            st.write(":red[26] Douze mois après, comme il se promenait sur la terrasse du palais royal de Babylone,")
            st.write(":red[27] le roi prit la parole et dit : « N’est-ce pas ici Babylone la grande ? Moi, je l’ai bâtie comme une maison royale, par la puissance de ma force et pour la gloire de ma majesté. »")
            st.write(":red[28] Ces paroles étaient encore dans sa bouche quand une voix tomba du ciel : « C’est à toi que l’on parle, ô roi Nabucodonosor ! On te retire la royauté.")
            st.write(":red[29] Tu seras chassé d’entre les hommes, tu auras ta demeure avec les animaux sauvages, on te nourrira d’herbe, comme les bœufs, et sept temps passeront sur toi, jusqu’au moment où tu reconnaîtras que le Très-Haut est maître du royaume des hommes et le donne à qui il veut. »")
            st.write(":red[30] À l’instant même, la parole s’accomplit pour Nabucodonosor : il fut chassé d’entre les hommes, il mangea de l’herbe comme les bœufs, son corps fut trempé de la rosée du ciel, jusqu’à ce que ses cheveux grandissent comme des plumes d’aigle, et ses ongles, comme des griffes d’oiseaux.")
            st.write(":red[31] « Au bout des jours fixés, moi, Nabucodonosor, je levai les yeux vers le ciel, et l’intelligence revint en moi. Alors, je bénis le Très-Haut, je célébrai l’éternel Vivant et lui rendis gloire : Son pouvoir est un pouvoir éternel, son royaume s’étend d’âge en âge.")
            st.write(":red[32] Tous les habitants de la terre sont comptés pour rien ; il fait ce qui lui plaît de l’armée du ciel et des habitants de la terre. Nul ne fait obstacle à sa main, personne ne lui dit : “Que fais-tu ?”")
            st.write(":red[33] À ce moment-là, l’intelligence me revint ; ma splendeur et mon éclat me revinrent aussi, pour la gloire de mon règne. Mes conseillers et les grands de mon royaume me réclamèrent. Je fus rétabli dans ma royauté, et un surcroît de grandeur me fut accordé.")
            st.write(":red[34] Maintenant, moi, Nabucodonosor, je bénis, j’exalte et célèbre le Roi du ciel : Toutes ses actions sont vérité, et ses chemins, justice ; il peut rabaisser ceux qui marchent dans l’arrogance.")


        elif chapitre_choice == 5:
            st.write(":red[01] Le roi Balthazar donna un somptueux festin pour les grands du royaume au nombre de mille, et il se mit à boire du vin en leur présence.")
            st.write(":red[02] Excité par le vin, il fit apporter les vases d’or et d’argent que son père Nabucodonosor avait enlevés au temple de Jérusalem ; il voulait y boire, avec ses grands, ses épouses et ses concubines.")
            st.write(":red[03] On apporta donc les vases d’or enlevés du temple, de la Maison de Dieu à Jérusalem, et le roi, ses grands, ses épouses et ses concubines s’en servirent pour boire.")
            st.write(":red[04] Après avoir bu, ils entonnèrent la louange de leurs dieux d’or et d’argent, de bronze et de fer, de bois et de pierre.")
            st.write(":red[05] Soudain on vit apparaître, en face du candélabre, les doigts d’une main d’homme qui se mirent à écrire sur la paroi de la salle du banquet royal. Lorsque le roi vit cette main qui écrivait,")
            st.write(":red[06] il changea de couleur, son esprit se troubla, il fut pris de tremblement, et ses genoux s’entrechoquèrent.")
            st.write(":red[07] Le roi cria de faire entrer les mages, les devins et les astrologues. Il prit la parole et dit aux sages de Babylone : « L’homme qui lira cette inscription et me l’interprétera, on le revêtira de pourpre, on lui mettra un collier d’or, et il sera le troisième personnage du royaume. »")
            st.write(":red[08] Tous les sages du roi entrèrent donc, mais ils ne purent lire l’inscription ni en donner au roi l’interprétation.")
            st.write(":red[09] Le roi Balthazar en était épouvanté : son visage changea de couleur, et les grands du royaume furent atterrés.")
            st.write(":red[10] La reine, alertée par les paroles du roi et des grands, entra dans la salle du banquet. Elle prit la parole et dit : « Ô roi, puisses-tu vivre à jamais ! Que tes pensées ne t’épouvantent pas, que ton visage ne change pas de couleur !")
            st.write(":red[11] Dans ton royaume, un homme possède en lui l’esprit des dieux saints. Du temps de ton père, on a trouvé en lui une lumière, une intelligence, et une sagesse pareille à la sagesse des dieux. Le roi Nabucodonosor, ton père, le nomma chef des magiciens, des mages, des devins et des astrologues. Il fit ainsi")
            st.write(":red[12] parce qu’on avait trouvé en ce Daniel – à qui le roi avait donné le nom de Beltassar – un esprit supérieur, une intelligence, une clairvoyance pour interpréter les songes, déchiffrer les énigmes et dénouer les difficultés. Donc, que Daniel soit appelé, et il donnera l’interprétation. »")
            st.write(":red[13] On fit venir Daniel devant le roi, et le roi lui dit : « Es-tu bien Daniel, l’un de ces déportés amenés de Juda par le roi mon père ?")
            st.write(":red[14] J’ai entendu dire qu’un esprit des dieux réside en toi, et qu’on trouve chez toi une clairvoyance, une intelligence et une sagesse extraordinaires.")
            st.write(":red[15] Et maintenant on a fait venir en ma présence les sages et les mages pour lire cette inscription et m’en faire connaître l’interprétation. Mais ils n’ont pas été capables de me la donner.")
            st.write(":red[16] J’ai entendu dire aussi que tu es capable de donner des interprétations et de résoudre des questions difficiles. Si tu es capable de lire cette inscription et de me l’interpréter, tu seras revêtu de pourpre, tu porteras un collier d’or et tu seras le troisième personnage du royaume. »")
            st.write(":red[17] Daniel répondit au roi : « Garde tes cadeaux, et offre à d’autres tes présents ! Moi, je lirai au roi l’inscription et je lui en donnerai l’interprétation.")
            st.write(":red[18] Ô roi, le Dieu Très-Haut avait donné à ton père le roi Nabucodonosor la royauté, la grandeur, la gloire et la splendeur.")
            st.write(":red[19] La grandeur qui lui était donnée faisait trembler de crainte devant lui tous les peuples, nations et gens de toutes langues. Il tuait qui il voulait, laissait vivre qui il voulait ; il élevait qui il voulait, abaissait qui il voulait.")
            st.write(":red[20] Mais lorsque son cœur devint hautain, son esprit dur jusqu’à l’orgueil, il fut jeté à bas de son trône royal, et sa gloire lui fut retirée.")
            st.write(":red[21] On le chassa d’entre les hommes, son cœur devint comme celui des bêtes ; il demeura avec les ânes sauvages, on le nourrissait d’herbe comme les bœufs ; son corps était trempé par la rosée du ciel, jusqu’au moment où il reconnut que le Dieu Très-Haut est maître du royaume des hommes et place à sa tête qui il veut.")
            st.write(":red[22] Toi, son fils Balthazar, tu n’as pas abaissé ton cœur, et pourtant, tu savais tout cela.")
            st.write(":red[23] Tu t’es élevé contre le Seigneur du ciel ; tu t’es fait apporter les vases de sa Maison, et vous y avez bu du vin, toi, les grands de ton royaume, tes épouses et tes concubines ; vous avez entonné la louange de vos dieux d’or et d’argent, de bronze et de fer, de bois et de pierre, ces dieux qui ne voient pas, qui n’entendent pas, qui ne savent rien. Mais tu n’as pas rendu gloire au Dieu qui tient dans sa main ton souffle et tous tes chemins.")
            st.write(":red[24] C’est pourquoi il a envoyé cette main et fait tracer cette inscription.")
            st.write(":red[25] En voici le texte : Mené, Mené, Teqèl, Ou-Pharsine.")
            st.write(":red[26] Et voici l’interprétation de ces mots : Mené (c’est-à-dire “compté”) : Dieu a compté les jours de ton règne et y a mis fin ;")
            st.write(":red[27] Teqèl (c’est-à-dire “pesé”) : tu as été pesé dans la balance, et tu as été trouvé trop léger ;")
            st.write(":red[28] Ou-Pharsine (c’est-à-dire “partagé”) : ton royaume a été partagé et donné aux Mèdes et aux Perses. »")
            st.write(":red[29] Alors, Balthazar ordonna de revêtir Daniel de pourpre, de lui mettre au cou un collier d’or et de proclamer qu’il deviendrait le troisième personnage du royaume.")
            st.write(":red[30] Cette nuit-là, Balthazar, le roi des Chaldéens, fut tué.")


        elif chapitre_choice == 6:
            st.write(":red[01] Darius le Mède reçut le royaume. Il avait soixante-deux ans.")
            st.write(":red[02] Darius jugea bon d’établir sur son royaume cent vingt satrapes, pour tout le royaume,")
            st.write(":red[03] et au-dessus d’eux, trois ministres, auxquels ces satrapes rendraient des comptes, pour que le roi ne soit pas lésé. L’un d’entre eux était Daniel.")
            st.write(":red[04] Or, Daniel l’emporta sur les autres ministres et les satrapes, parce qu’il avait en lui un esprit supérieur. Le roi avait l’intention de le placer à la tête de tout le royaume.")
            st.write(":red[05] Pour cette raison, les ministres et les satrapes cherchaient à prendre Daniel en faute dans les affaires du royaume, mais ils ne pouvaient trouver ni faute ni erreur, parce qu’il était fidèle et qu’on ne pouvait lui imputer ni négligence ni erreur.")
            st.write(":red[06] Ces hommes dirent : « Nous ne trouvons aucune faute en Daniel ; trouvons-en une à propos de la loi de son Dieu. »")
            st.write(":red[07] Alors, ces ministres et ces satrapes se précipitèrent chez le roi et lui parlèrent ainsi : « Ô roi Darius, puisses-tu vivre à jamais !")
            st.write(":red[08] Après concertation, tous les ministres du royaume, les préfets, les satrapes, les conseillers et les gouverneurs te proposent de promulguer un décret pour donner force de loi à l’interdiction suivante : Tout homme qui, dans les trente jours à venir, adressera une prière à un autre dieu ou à un autre homme que toi, ô roi, sera jeté dans la fosse aux lions.")
            st.write(":red[09] Maintenant, ô roi, promulgue cette interdiction, fais-la mettre par écrit afin qu’on n’y change rien, selon la loi irrévocable des Mèdes et des Perses. »")
            st.write(":red[10] Et le roi Darius fit mettre l’interdiction par écrit.")
            st.write(":red[11] Lorsque Daniel sut que l’acte avait été rédigé, il entra dans sa maison. Les fenêtres de sa chambre la plus haute s’ouvraient en direction de Jérusalem et, trois fois par jour, il se mettait à genoux, s’adonnant à l’intercession et à la louange en présence de son Dieu, comme il l’avait toujours fait.")
            st.write(":red[12] Les hommes qui avaient comploté contre lui se précipitèrent et le surprirent en train de prier et de supplier en présence de son Dieu.")
            st.write(":red[13] Ils allèrent trouver le roi et lui dirent : « N’as-tu pas fait mettre par écrit cette interdiction : Tout homme qui, dans les trente jours à venir, adressera une prière à un dieu ou à un homme autre que le roi, sera jeté dans la fosse aux lions ? » Le roi répondit : « Oui, c’est la décision que j’ai prise. Et, selon la loi des Mèdes et des Perses, elle est irrévocable. »")
            st.write(":red[14] Ils dirent alors au roi : « Daniel, un des déportés de Juda, ne tient compte ni de toi, ni de ton interdiction, ô roi ; trois fois par jour, il fait sa prière. »")
            st.write(":red[15] En apprenant cela, le roi fut très contrarié et se préoccupa de sauver Daniel. Jusqu’au coucher du soleil, il chercha comment le soustraire à la mort.")
            st.write(":red[16] Les mêmes hommes revinrent à la charge auprès du roi : « N’oublie pas, ô roi, que, selon la loi des Mèdes et des Perses, toute interdiction, tout décret porté par le roi est irrévocable. »")
            st.write(":red[17] Alors le roi ordonna d’emmener Daniel, et on le jeta dans la fosse aux lions. Il dit à Daniel : « Ton Dieu, que tu sers avec tant de constance, c’est lui qui te délivrera ! »")
            st.write(":red[18] On apporta une plaque de pierre, on la plaça sur l’ouverture de la fosse ; le roi la scella avec le cachet de son anneau et celui des grands du royaume, pour que la condamnation de Daniel fût irrévocable.")
            st.write(":red[19] Puis le roi rentra dans son palais ; il passa la nuit sans manger ni boire, il ne fit venir aucune concubine, il ne put trouver le sommeil.")
            st.write(":red[20] Il se leva dès l’aube, au petit jour, et se rendit en hâte à la fosse aux lions.")
            st.write(":red[21] Arrivé près de la fosse, il appela Daniel d’une voix angoissée : « Daniel, serviteur du Dieu vivant, ton Dieu, que tu sers avec tant de constance, a-t-il pu te faire échapper aux lions ? »")
            st.write(":red[22] Daniel répondit : « Ô roi, puisses-tu vivre à jamais !")
            st.write(":red[23] Mon Dieu a envoyé son ange, qui a fermé la gueule des lions. Ils ne m’ont fait aucun mal, car j’avais été reconnu innocent devant lui ; et devant toi, ô roi, je n’avais rien fait de criminel. »")
            st.write(":red[24] Le roi ressentit une grande joie et ordonna de tirer Daniel de la fosse. On l’en retira donc, et il n’avait aucune blessure, car il avait eu foi en son Dieu.")
            st.write(":red[25] Le roi ordonna d’amener les accusateurs de Daniel et de les jeter dans la fosse aux lions, avec leurs enfants et leurs femmes ; or, avant même qu’ils soient au fond de la fosse, les lions les avaient happés et leur avaient broyé les os.")
            st.write(":red[26] Alors le roi Darius écrivit à tous les peuples, nations et gens de toutes langues, qui habitent sur toute la terre : « Que votre paix soit grande !")
            st.write(":red[27] Voici l’ordre que je donne : Dans toute l’étendue de mon empire, on doit trembler de crainte devant le Dieu de Daniel, car il est le Dieu vivant, il demeure éternellement ; son règne ne sera pas détruit, sa souveraineté n’aura pas de fin.")
            st.write(":red[28] Il délivre et il sauve, il accomplit des signes et des prodiges, au ciel et sur la terre, lui qui a sauvé Daniel de la griffe des lions. »")
            st.write(":red[29] Daniel, quant à lui, prospéra sous le règne de Darius et sous le règne de Cyrus le Perse.")

        elif chapitre_choice == 7:
            st.write(":red[01] La première année du règne de Balthazar, roi de Babylone, Daniel eut, sur son lit, un songe et des visions dans son esprit. Alors, il mit le songe par écrit. Début du récit.")
            st.write(":red[02] Daniel prit la parole et dit : « Au cours de la nuit, dans ma vision, je regardais. Les quatre vents du ciel soulevaient la grande mer.")
            st.write(":red[03] Quatre bêtes énormes sortirent de la mer, chacune différente des autres.")
            st.write(":red[04] La première ressemblait à un lion, et elle avait des ailes d’aigle. Tandis que je la regardais, ses ailes lui furent arrachées, et elle fut soulevée de terre et dressée sur ses pieds, comme un homme, et un cœur d’homme lui fut donné.")
            st.write(":red[05] La deuxième bête ressemblait à un ours ; elle était à moitié debout, et elle avait trois côtes d’animal dans la gueule, entre les dents. On lui dit : “Lève-toi, dévore beaucoup de viande !”")
            st.write(":red[06] Je continuais à regarder : je vis une autre bête, qui ressemblait à une panthère ; et elle avait quatre ailes d’oiseau sur le dos ; elle avait aussi quatre têtes. La domination lui fut donnée.")
            st.write(":red[07] Puis, au cours de la nuit, je regardais encore ; je vis une quatrième bête, terrible, effrayante, extraordinairement puissante ; elle avait des dents de fer énormes ; elle dévorait, déchiquetait et piétinait tout ce qui restait. Elle était différente des trois autres bêtes, et elle avait dix cornes.")
            st.write(":red[08] Comme je considérais ces cornes, il en poussa une autre, plus petite, au milieu ; trois des premières cornes furent arrachées devant celle-ci. Et cette corne avait des yeux comme des yeux d’homme, et une bouche qui tenait des propos délirants.")
            st.write(":red[09] Je continuai à regarder : des trônes furent disposés, et un Vieillard prit place ; son habit était blanc comme la neige, et les cheveux de sa tête, comme de la laine immaculée ; son trône était fait de flammes de feu, avec des roues de feu ardent.")
            st.write(":red[10] Un fleuve de feu coulait, qui jaillissait devant lui. Des milliers de milliers le servaient, des myriades de myriades se tenaient devant lui. Le tribunal prit place et l’on ouvrit des livres.")
            st.write(":red[11] Je regardais, j’entendais les propos délirants que vomissait la corne. Je regardais, et la bête fut tuée, son cadavre fut jeté au feu.")
            st.write(":red[12] Quant aux autres bêtes, la domination leur fut retirée, mais une prolongation de vie leur fut donnée, pour une période et un temps déterminés.")
            st.write(":red[13] Je regardais, au cours des visions de la nuit, et je voyais venir, avec les nuées du ciel, comme un Fils d’homme ; il parvint jusqu’au Vieillard, et on le fit avancer devant lui.")
            st.write(":red[14] Et il lui fut donné domination, gloire et royauté ; tous les peuples, toutes les nations et les gens de toutes langues le servirent. Sa domination est une domination éternelle, qui ne passera pas, et sa royauté, une royauté qui ne sera pas détruite.")
            st.write(":red[15] Moi, Daniel, j’avais l’esprit angoissé, car les visions que j’avais me bouleversaient.")
            st.write(":red[16] Je m’approchai de l’un de ceux qui entouraient le Trône, et je l’interrogeai sur la vérité de tout cela. Il me répondit et me révéla l’interprétation :")
            st.write(":red[17] ”Ces bêtes énormes, au nombre de quatre, ce sont quatre rois qui surgiront de la terre.")
            st.write(":red[18] Mais ce sont les saints du Très-Haut qui recevront la royauté et la posséderont pour toute l’éternité.”")
            st.write(":red[19] Puis je l’interrogeai sur la quatrième bête, qui était différente de toutes les autres, cette bête terriblement puissante, avec ses dents de fer et ses griffes de bronze, qui dévorait, déchiquetait et piétinait tout ce qui restait.")
            st.write(":red[20] Je l’interrogeai sur les dix cornes de sa tête, et sur cette corne qui lui avait poussé en faisant tomber les trois autres devant elle – cette corne qui avait des yeux, et une bouche qui tenait des propos délirants – cette corne qui était plus imposante que les autres.")
            st.write(":red[21] Je l’avais vue faire la guerre aux saints et l’emporter sur eux,")
            st.write(":red[22] jusqu’à la venue du Vieillard qui avait prononcé le jugement en faveur des saints du Très-Haut, et le temps était arrivé où les saints avaient pris possession de la royauté.")
            st.write(":red[23] À ces questions, il me fut répondu : “La quatrième bête, c’est un quatrième royaume sur la terre, qui sera différent de tous les royaumes. Il dévorera toute la terre, la piétinera et l’écrasera.")
            st.write(":red[24] Les dix cornes, ce sont dix rois qui surgiront de ce royaume-là. Un autre roi surgira ensuite ; il sera différent des précédents, et il renversera trois rois.")
            st.write(":red[25] Il prononcera des paroles hostiles au Très-Haut, il persécutera les saints du Très-Haut, et il entreprendra de changer la date des fêtes et la Loi. Les saints seront livrés à son pouvoir pendant un temps, des temps, et la moitié d’un temps.")
            st.write(":red[26] Puis le tribunal siégera, et la domination sera enlevée à ce royaume, qui sera détruit et totalement anéanti.")
            st.write(":red[27] La royauté, la domination et la puissance de tous les royaumes de la terre, sont données au peuple des saints du Très-Haut. Sa royauté est une royauté éternelle, et tous les empires le serviront et lui obéiront.” »")
            st.write(":red[28] Ici finit le récit. Moi, Daniel, ce que je pensais m’épouvanta fortement et mon visage changea de couleur. Je gardai dans mon cœur ces événements.")


        elif chapitre_choice == 8:
            st.write(":red[01] La troisième année du règne du roi Balthazar, une vision m’est apparue, à moi, Daniel, après celle qui m’était apparue précédemment.")
            st.write(":red[02] Je regardai, et voici que, dans la vision, j’étais à Suse-la-Citadelle dans la province d’Élam, près de la rivière Oulaï.")
            st.write(":red[03] Je levai les yeux, et voici que je vis un bélier se tenant face à la rivière. Il avait deux cornes, deux hautes cornes, mais l’une plus haute que l’autre, et la plus haute se dressa en dernier.")
            st.write(":red[04] Je vis le bélier donner des coups de corne vers l’ouest, vers le nord, vers le sud. Aucune bête ne pouvait tenir debout devant lui, personne ne pouvait lui échapper. Il agissait selon son bon plaisir et ne cessait de grandir.")
            st.write(":red[05] Moi, j’étais en train de réfléchir, et voici qu’un bouc arriva de l’occident, survolant toute la terre sans toucher le sol. Il avait une corne imposante entre les yeux.")
            st.write(":red[06] Il s’approcha du bélier à deux cornes que j’avais vu dressé face à la rivière et se rua vers lui de toute sa force.")
            st.write(":red[07] Je le vis atteindre le bélier et se mettre en rage contre lui, puis le frapper et briser ses deux cornes. Le bélier n’avait pas la force de lui faire face. Il le jeta à terre et le piétina. Personne ne pouvait en délivrer le bélier.")
            st.write(":red[08] Le bouc ne cessait de croître mais, au sommet de sa puissance, la grande corne se brisa. Quatre cornes imposantes poussèrent à sa place, orientées vers les quatre points cardinaux.")
            st.write(":red[09] De l’une d’elle, une toute petite corne sortit, mais qui grandit vers le sud, vers l’est, et vers le Pays magnifique.")
            st.write(":red[10] Elle grandit jusqu’à l’armée du ciel, elle terrassa une partie de cette armée et des étoiles, elle les piétina.")
            st.write(":red[11] Elle grandit même jusqu’au chef de l’armée, le sacrifice perpétuel fut retiré à celui-ci, et les fondations de son Lieu saint furent renversées.")
            st.write(":red[12] Et une armée fut postée contre le sacrifice perpétuel de façon perverse. La corne jeta la vérité par terre. Ce qu’elle entreprit, elle le réussit.")
            st.write(":red[13] Un être saint parla, je l’entendis ; et un autre saint lui répondit : « Combien de temps verrons-nous le sacrifice perpétuel retiré, la perversité dévastatrice, le sanctuaire livré, l’armée piétinée ? »")
            st.write(":red[14] Il lui dit : « Encore deux mille trois cents soirs et matins, et le Lieu saint sera rétabli dans ses droits. »")
            st.write(":red[15] Tandis que moi, Daniel, je regardais la vision en cherchant à comprendre, voici que se tenait en face de moi quelqu’un ayant l’apparence d’un homme.")
            st.write(":red[16] Et j’entendis la voix de l’homme entre les rives de l’Oulaï. Il cria : « Gabriel, fais-lui comprendre la vision ! »")
            st.write(":red[17] Il s’avança vers le lieu où je me tenais. À son approche, je fus effrayé et je tombai face contre terre. Il me dit : « Fils d’homme, comprends ! La vision concerne le temps de la fin. »")
            st.write(":red[18] Tandis qu’il me parlait, je m’évanouis, la face contre terre. Il me toucha et me fit mettre debout à l’endroit où j’étais.")
            st.write(":red[19] Il dit : « Je vais te faire savoir ce qui arrivera au terme de la colère, car la fin est pour le moment fixé.")
            st.write(":red[20] Le bélier à deux cornes que tu as vu, ce sont les deux rois de Médie et de Perse.")
            st.write(":red[13] Le roi s’entretint avec eux, et pas un seul n’était comparable à Daniel, Ananias, Misaël et Azarias. Ils entrèrent donc au service du roi.")
            st.write(":red[14] Sur toutes les questions demandant sagesse et intelligence que le roi leur posait, il les trouvait dix fois supérieurs à tous les magiciens et mages de tout son royaume.")
            st.write(":red[15] Et Daniel vécut jusqu’à la première année du roi Cyrus.")
            st.write(":red[21] Le bouc velu, c’est le roi de Grèce, et la grande corne entre ses yeux, c’est le premier roi.")
            st.write(":red[22] Si elle s’est brisée et que quatre ont surgi à sa place, c’est que quatre royaumes surgiront de sa nation, mais sans avoir sa force.")
            st.write(":red[23] Au terme de leur règne, quand les pécheurs auront atteint le comble de leur perversité, se lèvera un roi au visage fier, sachant pénétrer les énigmes.")
            st.write(":red[24] Sa puissance se renforcera – mais non par sa propre puissance –, il opérera des destructions prodigieuses, il réussira dans ce qu’il entreprendra, il détruira des puissants et le peuple des saints.")
            st.write(":red[25] Par son habileté, il assurera le succès de ses tromperies ; son cœur s’enflera d’orgueil et, dans la tranquillité, il détruira une multitude. Il se dressera contre le Prince des princes, mais il sera brisé sans l’intervention de personne.")
            st.write(":red[26] Ce que tu as vu et ce qui a été dit au sujet des soirs et des matins, c’est la vérité. Mais toi, garde secrète la vision, car elle concerne des jours lointains.")
            st.write(":red[27] Et moi, Daniel, je m’évanouis et je fus malade pendant plusieurs jours. Puis je me levai et accomplis mon office auprès du roi ; j’étais terrifié par ce que j’avais vu, mais personne ne comprenait.")


        elif chapitre_choice == 9:
            st.write(":red[01] La première année du règne de Darius, fils d’Assuérus, de la race des Mèdes, qui était devenu roi des Chaldéens,")
            st.write(":red[02] la première année de son règne, moi, Daniel, je déchiffrais dans les livres le nombre d’années qui, selon la parole adressée par le Seigneur au prophète Jérémie, devaient s’écouler avant que prenne fin la ruine de Jérusalem : soixante-dix ans.")
            st.write(":red[03] Tournant le visage vers le Seigneur Dieu, je lui offris mes prières et mes supplications dans le jeûne, le sac et la cendre.")
            st.write(":red[04] Je fis au Seigneur mon Dieu cette prière et cette confession : « Ah ! toi Seigneur, le Dieu grand et redoutable, qui garde alliance et fidélité à ceux qui l’aiment et qui observent ses commandements,")
            st.write(":red[05] nous avons péché, nous avons commis l’iniquité, nous avons fait le mal, nous avons été rebelles, nous nous sommes détournés de tes commandements et de tes ordonnances.")
            st.write(":red[06] Nous n’avons pas écouté tes serviteurs les prophètes, qui ont parlé en ton nom à nos rois, à nos princes, à nos pères, à tout le peuple du pays.")
            st.write(":red[07] À toi, Seigneur, la justice ; à nous la honte au visage, comme on le voit aujourd’hui pour les gens de Juda, pour les habitants de Jérusalem et de tout Israël, pour ceux qui sont près et pour ceux qui sont loin, dans tous les pays où tu les as chassés, à cause des infidélités qu’ils ont commises envers toi.")
            st.write(":red[08] Seigneur, à nous la honte au visage, à nos rois, à nos princes, à nos pères, parce que nous avons péché contre toi.")
            st.write(":red[09] Au Seigneur notre Dieu, la miséricorde et le pardon, car nous nous sommes révoltés contre lui,")
            st.write(":red[10] nous n’avons pas écouté la voix du Seigneur, notre Dieu, car nous n’avons pas suivi les lois qu’il nous proposait par ses serviteurs les prophètes.")
            st.write(":red[11] Tout Israël a transgressé ta loi, il s’est détourné sans écouter ta voix. Alors, les malédictions et les menaces inscrites dans la loi de Moïse, le serviteur de Dieu, se sont répandues sur nous, parce que nous avons péché contre le Seigneur.")
            st.write(":red[12] Celui-ci a mis à exécution les paroles prononcées contre nous et contre nos gouvernants. Il a fait venir contre nous une calamité si grande que, nulle part, il ne s’en est produit de semblable sous les cieux, sauf à Jérusalem.")
            st.write(":red[13] Tout ce malheur est venu sur nous, selon ce qui est écrit dans la loi de Moïse. Mais nous n’avons pas apaisé la face du Seigneur notre Dieu, puisque nous ne sommes pas revenus de nos fautes en prêtant attention à la vérité.")
            st.write(":red[14] Le Seigneur a veillé à ce que le malheur nous atteigne, car le Seigneur notre Dieu est juste en tout ce qu’il accomplit, mais nous n’avons pas écouté sa voix.")
            st.write(":red[15] Et maintenant, Seigneur notre Dieu, toi qui, d’une main forte, as fait sortir ton peuple du pays d’Égypte, toi qui t’es fait un nom, comme on le voit aujourd’hui, nous avons péché et nous avons été coupables.")
            st.write(":red[16] Seigneur, en raison de toutes tes justes actions, que ta colère et ta fureur se détournent de Jérusalem, ta ville et ta montagne sainte ! Car à cause de nos péchés et des fautes de nos pères, Jérusalem et ton peuple sont objet d’insulte pour tous ceux qui nous environnent.")
            st.write(":red[17] Et maintenant, notre Dieu, écoute la prière de ton serviteur et ses supplications. Pour ta cause, Seigneur, fais briller ton visage sur ton Lieu saint dévasté.")
            st.write(":red[18] Mon Dieu, tends l’oreille et écoute, ouvre les yeux et regarde nos dévastations et la ville sur laquelle on invoque ton nom. Si nous déposons nos supplications devant toi, ce n’est pas au titre de nos œuvres de justice, mais de ta grande miséricorde.")
            st.write(":red[19] Seigneur, écoute ! Seigneur, pardonne ! Seigneur, sois attentif et agis ! Ne tarde pas ! C’est pour ta cause, mon Dieu, car c’est ton nom qui est invoqué sur ta ville et ton peuple ! »")
            st.write(":red[20] Je parlais encore, priant, confessant mon péché et le péché de mon peuple Israël, déposant ma supplication devant le Seigneur mon Dieu, pour la montagne sainte de mon Dieu ;")
            st.write(":red[21] je parlais encore dans ma prière quand Gabriel – l’être que j’avais vu au commencement de la vision – s’approcha de moi d’un vol rapide à l’heure de l’offrande du soir.")
            st.write(":red[22] Il m’instruisit, me parlant en ces termes : « Daniel, je suis sorti maintenant pour ouvrir ton intelligence.")
            st.write(":red[23] Dès le début de ta supplication, une parole a surgi, et je suis venu te l’annoncer, car toi, tu es aimé de Dieu. Comprends la parole et cherche à comprendre l’apparition.")
            st.write(":red[24] Soixante-dix semaines ont été fixées à ton peuple et à ta ville sainte, pour faire cesser la perversité et mettre un terme au péché, pour expier la faute et amener la justice éternelle, pour accomplir vision et prophétie, et consacrer le Saint des saints.")
            st.write(":red[25] Sache et comprends ! Depuis l’instant où fut donné l’ordre de rebâtir Jérusalem jusqu’à l’avènement d’un messie, un chef, il y aura sept semaines. Pendant soixante-deux semaines, on rebâtira les places et les remparts, mais ce sera dans la détresse des temps.")
            st.write(":red[26] Et après les soixante-deux semaines, un messie sera supprimé. Le peuple d’un chef à venir détruira la ville et le Lieu saint. Puis, dans un déferlement, sa fin viendra. Jusqu’à la fin de la guerre, les dévastations décidées auront lieu.")
            st.write(":red[27] Durant une semaine, ce chef renforcera l’alliance avec une multitude ; pendant la moitié de la semaine, il fera cesser le sacrifice et l’offrande, et sur une aile du Temple il y aura l’Abomination de la désolation, jusqu’à ce que l’extermination décidée fonde sur l’auteur de cette désolation. »")

        elif chapitre_choice == 10:
            st.write(":red[01] La troisième année du règne de Cyrus, roi de Perse, une parole fut révélée à Daniel, surnommé Beltassar : parole vraie et grand combat. Il comprit la parole : la compréhension lui vint dans une vision.")
            st.write(":red[02] En ces jours-là, moi, Daniel, je portai le deuil pendant trois semaines entières.")
            st.write(":red[03] Je ne mangeai pas de nourriture agréable ; ni viande ni vin ne passèrent par ma bouche, je m’abstins de tout parfum jusqu’au terme de ces trois semaines.")
            st.write(":red[04] Et le vingt-quatrième jour du premier mois, étant au bord du grand fleuve, le Tigre,")
            st.write(":red[05] je levai les yeux et regardai. Voici : il y avait un homme vêtu de lin, qui portait une ceinture d’or pur autour des reins ;")
            st.write(":red[06] son corps était comme de la chrysolithe, son visage comme un éclair, ses yeux comme des torches de feu, ses bras et ses jambes avaient l’éclat du bronze poli, et le son de ses paroles était comme la rumeur d’une multitude.")
            st.write(":red[07] Moi seul, Daniel, je vis cette apparition. Les hommes qui étaient avec moi ne voyaient pas l’apparition, mais une grande terreur s’abattit sur eux, et ils s’enfuirent pour se cacher.")
            st.write(":red[08] Je demeurai donc seul et regardai cette apparition impressionnante. J’étais sans force aucune, mes traits bouleversés se décomposèrent, ma force m’abandonna.")
            st.write(":red[09] J’entendis le bruit de ses paroles, et lorsque je l’entendis, je fus pris de torpeur et tombai face contre terre.")
            st.write(":red[10] Alors une main me toucha et me redressa sur les genoux et les paumes de mes mains.")
            st.write(":red[11] Il me dit : « Daniel, homme aimé de Dieu, comprends les paroles que je vais te dire, mets-toi debout. Oui, maintenant j’ai été envoyé vers toi. » Tandis qu’il me parlait, je me mis debout en tremblant.")
            st.write(":red[12] Il me dit : « N’aie pas peur, Daniel. Dès le premier jour où tu as eu à cœur de comprendre et de t’humilier devant ton Dieu, tes paroles ont été entendues : c’est à cause de tes paroles que je suis venu.")
            st.write(":red[13] L’ange du royaume de Perse m’a résisté pendant vingt et un jours, mais Michel, l’un des premiers anges, est venu à mon aide. Moi, je l’ai laissé avec l’ange des rois de Perse.")
            st.write(":red[14] Alors, je suis venu pour t’expliquer ce qui arrivera à ton peuple à la fin des jours. Voici une nouvelle vision pour ces jours-là. »")
            st.write(":red[15] Tandis qu’il me parlait, je me prosternai à terre en silence.")
            st.write(":red[16] Voici comme une forme de fils d’homme qui me toucha les lèvres. J’ouvris la bouche et parlai. Je dis à celui qui était devant moi : « Mon seigneur, à cause de l’apparition, l’angoisse me submerge et ma force m’abandonne.")
            st.write(":red[17] Comment le serviteur de mon seigneur pourra-t-il parler avec toi, mon seigneur, alors que je n’ai plus de force, et qu’il ne me reste pas de souffle ? »")
            st.write(":red[18] Celui qui avait l’apparence d’un homme me toucha de nouveau et me réconforta.")
            st.write(":red[19] Il me dit : « N’aie pas peur, homme aimé de Dieu ! La paix soit avec toi ! Sois très fort ! » Tandis qu’il parlait, je repris des forces et dis : « Que mon seigneur parle, car tu m’as rendu la force. »")
            st.write(":red[20] Il dit : « Sais-tu pourquoi je suis venu vers toi ? Maintenant, je vais retourner combattre l’ange de la Perse. À l’issue de ce combat, l’ange de la Grèce viendra.")
            st.write(":red[21] Personne ne me prête main-forte contre ceux-ci, sauf Michel, votre ange. Mais je t’annonce ce qui est inscrit dans le livre de vérité.")


        elif chapitre_choice == 11:
            st.write(":red[01] La première année du règne de Darius le Mède, j’étais auprès de lui pour lui donner force et appui.")
            st.write(":red[02] Maintenant je vais te révéler une vérité : Voici que trois rois surgiront encore en Perse. Le quatrième les surpassera en richesse, et lorsque sa richesse l’aura rendu plus fort, il mobilisera tout contre le royaume de Grèce.")
            st.write(":red[03] Un roi puissant surgira, exercera un immense pouvoir et agira selon son bon plaisir.")
            st.write(":red[04] Mais à peine aura-t-il surgi que son royaume sera mis en pièces et partagé aux quatre vents du ciel, sans aucun profit pour ses descendants. Son pouvoir ne sera plus le même, car son royaume sera démembré et livré à d’autres.")
            st.write(":red[05] Le roi du Midi deviendra fort, mais l’un de ses princes sera plus fort que lui, son pouvoir sera plus grand que le sien.")
            st.write(":red[06] Après quelques années, ils feront alliance. La fille du roi du Midi viendra chez le roi du Nord pour exécuter ces accords. Mais elle n’aura plus d’appui et sa descendance ne se maintiendra pas. Elle-même sera livrée avec ceux qui l’avaient accompagnée, son enfant et celui qui était son soutien en ces temps-là.")
            st.write(":red[07] Mais de ses racines, un rejeton surgira à sa place. Il se portera à la rencontre de l’armée et entrera dans la citadelle du roi du Nord ; il les combattra et l’emportera.")
            st.write(":red[08] Il emmènera même leurs dieux comme captifs en Égypte, avec leurs images de métal fondu et leurs objets précieux d’argent et d’or. Pendant quelques années, il restera loin du roi du Nord.")
            st.write(":red[09] Mais ce dernier viendra dans le royaume du roi du Midi, puis retournera dans son pays.")
            st.write(":red[10] Ses fils reprendront le combat et réuniront des armées en grand nombre. L’un d’entre eux arrivera, déferlera, traversera, puis il s’en retournera. Ils porteront le combat jusqu’à la citadelle.")
            st.write(":red[11] Alors, le roi du Midi sera pris de rage. Il ira combattre contre le roi du Nord, qui mettra sur pied une troupe nombreuse, mais cette troupe sera livrée aux mains du roi du Midi.")
            st.write(":red[12] Quand la troupe aura été prise, son cœur s’enflera d’orgueil. Mais il aura beau abattre des myriades d’hommes, il n’en sera pas plus fort.")
            st.write(":red[13] Le roi du Nord mettra de nouveau sur pied une troupe, plus nombreuse que la précédente. Au bout d’un certain temps, de quelques années, il arrivera avec une grande armée et un équipement considérable.")
            st.write(":red[14] En ces temps-là, beaucoup se dresseront contre le roi du Midi. Des hommes violents de ton peuple se lèveront pour accomplir la vision, mais ils échoueront.")
            st.write(":red[15] Alors, le roi du Nord arrivera, il élèvera un remblai pour s’emparer d’une ville fortifiée. Les forces du roi du Midi ne résisteront pas, ni leur élite : elles n’en auront pas la force.")
            st.write(":red[16] Celui qui s’avancera contre ce dernier agira selon son bon plaisir. Nul ne lui résistera, et il s’arrêtera au Pays magnifique, ayant en main le pouvoir de détruire.")
            st.write(":red[17] Il se proposera de venir s’emparer de tout le royaume du roi du Midi et de passer accord avec lui. Il lui donnera une femme pour le conduire à sa perte, mais cela ne réussira pas, cela ne se produira pas.")
            st.write(":red[18] Il se tournera alors vers les îles et s’emparera de beaucoup d’entre elles, mais un général mettra fin à cette agression sans qu’il puisse à son tour l’agresser.")
            st.write(":red[19] Alors, il se tournera vers les citadelles de son pays. Mais il échouera, il tombera et on ne le retrouvera plus.")
            st.write(":red[20] Quelqu’un surgira à sa place, qui enverra un pillard attenter à ce qui fait la Splendeur du royaume. Mais en quelques jours il sera brisé, bien que ce ne soit ni par la colère ni par la guerre.")
            st.write(":red[21] À sa place surgira un homme méprisable à qui l’on n’accordera pas l’honneur de la royauté, mais il viendra, en toute tranquillité, s’emparer de la royauté par des intrigues.")
            st.write(":red[22] Devant lui, les forces d’invasion seront débordées et brisées, ainsi qu’un chef de l’Alliance.")
            st.write(":red[23] Par des accords passés avec lui, il agira en traître ; il montera en puissance et, avec peu de monde, il s’imposera.")
            st.write(":red[24] En toute tranquillité, il viendra dans les régions fertiles de la province. Il fera ce que ni ses pères ni les pères de ses pères n’avaient fait : il distribuera aux siens du butin, des dépouilles et de l’équipement. Il tramera des complots contre les villes fortes, mais pour un temps seulement.")
            st.write(":red[25] Il mettra sa force et son courage à s’acharner contre le roi du Midi, avec une grande armée. Le roi du Midi s’engagera dans la guerre avec une armée nombreuse et très puissante, mais il ne résistera pas, car on tramera des complots contre lui.")
            st.write(":red[26] Ceux qui partagent sa table l’anéantiront, son armée sera débordée et beaucoup de victimes tomberont.")
            st.write(":red[27] Les deux rois, le cœur mauvais, débiteront des mensonges à la même table, mais sans succès, car cela ne prendra fin qu’au moment fixé.")
            st.write(":red[28] Le roi du Nord retournera dans son pays avec un équipement considérable. Ayant des intentions hostiles contre l’Alliance sainte, il les mettra à exécution, puis il retournera dans son pays.")
            st.write(":red[29] Au moment fixé, il reviendra dans le royaume du Midi, mais cette fois, ce ne sera pas comme la première fois.")
            st.write(":red[30] Des navires venus de l’Occident l’attaqueront et il sera découragé. De nouveau, il s’emportera et agira contre l’Alliance sainte ; de nouveau, il sera de connivence avec ceux qui abandonnent l’Alliance sainte.")
            st.write(":red[31] Des forces envoyées par lui surgiront, profaneront le Lieu saint, la citadelle ; elles feront cesser le sacrifice perpétuel et établiront l’Abomination de la désolation.")
            st.write(":red[32] Ceux qui transgressent l’Alliance, il en fera des renégats par ses intrigues, mais le peuple de ceux qui connaissent leur Dieu réagira fermement.")
            st.write(":red[33] Les gens intelligents du peuple en instruiront beaucoup, mais ils seront accablés par l’épée, le feu, la captivité et la spoliation pendant des jours.")
            st.write(":red[34] Lorsqu’ils seront accablés, peu de gens leur viendront en aide, mais beaucoup se joindront à eux par intrigue.")
            st.write(":red[35] Parmi les gens intelligents, certains seront accablés ; ils seront ainsi épurés, purifiés, blanchis, jusqu’au temps de la fin, car ce n’est pas encore le moment fixé.")
            st.write(":red[36] Le roi agira selon son bon plaisir, il s’élèvera et s’enflera d’orgueil au-dessus de tout dieu. À propos du Dieu des dieux, il dira des choses aberrantes. Il réussira jusqu’à ce que la colère soit à son comble, car ce qui a été décidé s’accomplira.")
            st.write(":red[37] Il n’aura d’égard ni pour le dieu de ses pères, ni pour le dieu favori des femmes, il n’aura d’égard pour aucune divinité, car il s’enflera d’orgueil au-dessus de tout.")
            st.write(":red[38] À leur place, il honorera la divinité des citadelles, une divinité inconnue de ses pères ; il l’honorera avec de l’or, de l’argent, des pierres rares et des objets précieux.")
            st.write(":red[39] Il interviendra contre les fortifications des citadelles avec l’aide d’une divinité étrangère. Il comblera d’honneurs ceux qui la reconnaîtront, il leur donnera autorité sur beaucoup et distribuera des terres en récompense.")
            st.write(":red[40] Au temps de la fin, le roi du Midi l’affrontera. Le roi du Nord fondra sur celui-ci avec ses chars, ses cavaliers et de nombreux navires. Il arrivera dans les pays, il y déferlera, il les traversera.")
            st.write(":red[41] Il arrivera jusqu’au Pays magnifique et beaucoup seront accablés. Voici ceux qui échapperont à son emprise : Édom, Moab et les meilleurs des fils d’Ammone.")
            st.write(":red[42] Il étendra son emprise sur les pays ; même le pays d’Égypte n’en réchappera pas.")
            st.write(":red[43] Il s’emparera des trésors d’argent et d’or et de tous les objets précieux de l’Égypte. Les Libyens et les Éthiopiens marcheront dans ses pas.")
            st.write(":red[44] Mais des rumeurs venues de l’Orient et du Nord l’inquiéteront, et il partira en grande fureur pour détruire et anéantir beaucoup de monde.")
            st.write(":red[45] Il dressera les tentes de son quartier général entre la mer et la sainte Montagne magnifique. Mais ce sera pour lui la fin, sans que personne lui vienne en aide.")

        elif chapitre_choice == 12:
            st.write(":red[01] En ce temps-là se lèvera Michel, le chef des anges, celui qui se tient auprès des fils de ton peuple. Car ce sera un temps de détresse comme il n’y en a jamais eu depuis que les nations existent, jusqu’à ce temps-ci. Mais en ce temps-ci, ton peuple sera délivré, tous ceux qui se trouveront inscrits dans le Livre.")
            st.write(":red[02] Beaucoup de gens qui dormaient dans la poussière de la terre s’éveilleront, les uns pour la vie éternelle, les autres pour la honte et la déchéance éternelles.")
            st.write(":red[03] Ceux qui ont l’intelligence resplendiront comme la splendeur du firmament, et ceux qui sont des maîtres de justice pour la multitude brilleront comme les étoiles pour toujours et à jamais.")
            st.write(":red[04] Et toi, Daniel, tiens secrètes ces paroles, garde le Livre scellé jusqu’au temps de la fin. Beaucoup seront perplexes, mais la connaissance augmentera.")
            st.write(":red[05] Et moi, Daniel, je regardai : Voici que deux autres hommes se tenaient, chacun sur une rive du fleuve.")
            st.write(":red[06] L’un d’eux dit à celui qui, vêtu de lin, se tenait au-dessus des eaux du fleuve : « À quand la fin de ces choses surprenantes ? »")
            st.write(":red[07] J’entendis l’homme vêtu de lin qui se tenait au-dessus des eaux du fleuve. Il leva la main droite et la main gauche vers le ciel et jura par Celui qui vit à jamais : « Pendant un temps, des temps, et la moitié d’un temps. Lorsque la force du peuple saint sera entièrement brisée, tout cela s’arrêtera. »")
            st.write(":red[08] Et moi, j’entendis sans comprendre. J’insistai : « Mon seigneur, quel sera le terme de tout cela ? »")
            st.write(":red[09] Il dit : « Va, Daniel, car ces paroles resteront secrètes et scellées jusqu’au temps de la fin. »")
            st.write(":red[10] Beaucoup seront purifiés, blanchis, épurés. Les méchants feront le mal, aucun d’entre eux ne comprendra, mais ceux qui ont l’intelligence comprendront.")
            st.write(":red[11] Depuis l’instant où le sacrifice perpétuel aura cessé, quand l’Abomination de la désolation sera installée, 1 290 jours passeront.")
            st.write(":red[12] Heureux celui qui attendra et parviendra à 1 335 jours !")
            st.write(":red[13] Et toi, va jusqu’à la fin. Tu te reposeras, puis tu te tiendras debout pour recevoir ta part à la fin des jours.")



    with col2:
        st.write(":blue[Ta progression :]")
        # Affichage de la jauge de progression sans division par 100
        st.progress(st.session_state.progression)
        st.write(f"{st.session_state.progression:.2f}%")

        termine = st.checkbox("Coche puis met à jour 👇 si tu as terminé le chapitre 💪", chapitre_info["Terminé"] == 1)

        if st.button("Mettre à jour"):
            updated_data = update_excel(chapitre_choice, int(termine))
            update_progression(updated_data)
            st.success("Mise à jour effectuée.")

main()
